apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: cd-jenkins
          servicePort: 8080