apiVersion: v1
kind: Service
metadata:
  name: cd-jenkins-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: cd-jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001